### ISSUE TITLE
Registration and Forgot Password Screen

### ISSUE THREAD

**Issue by ManiDeepakReddyAila** [BigDataIA-Spring2023-Team-05/Assignment-03#28]
1. Forgot Password screen is not available for the user directly instead should use it from the Login Screen
2. Register screen has the same issue

**Comment by Charan-Patnaik** [comment]
Yes this was added as  a functionality to avoid unrelated jumps from one UI page to another , simply put this design logic was to stream line the user journey through the application.
With the constraints of streamlit framework  in  mind , the decision was made to use the above procedure

**Comment by Charan-Patnaik** [comment]
This is not a UI/UX issue , for example in facebook /  amazon etc you can jump into forgot password without going through login page

**Comment by ManiDeepakReddyAila** [comment]
> This is not a UI/UX issue , for example in facebook / amazon etc you can jump into forgot password without going through login page

Yes, user should be able to jump to forgot password without going through login page, but that was not the case here, it says "Please use Login Page"

But this was just a suggestion anyways.
